spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/myrealm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/myrealm
server:
  port: 8084